// magicnetTypes.js

const MAGICNET_EVENT_TYPES = {
    NOT_USED: "MAGICNET_EVENT_TYPE_NOT_USED",
    TEST: "MAGICNET_EVENT_TYPE_TEST",
    NEW_BLOCK: "MAGICNET_EVENT_TYPE_NEW_BLOCK"
};

module.exports = MAGICNET_EVENT_TYPES;
